default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: im_graetzl_development

test:
  <<: *default
  database: im_graetzl_test

production:
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false
