language: ruby
rvm:
 - '2.0.0'
 - '2.1.0'
 - '2.2.0'
 - '2.2.2'
cache: bundler
before_script:
- bundle exec rake db:schema:load RAILS_ENV=test
notifications:
  email:
    recipients:
      - klappradla@gmail.com
      - peter.tilg@gmail.com
    on_success: always
    on_failure: always
