# settings
option_settings:
  - namespace: 'aws:elasticbeanstalk:application:environment'
    option_name: RAILS_SKIP_MIGRATIONS
    value: true

# install git to be able to bundle gems from github
packages:
  yum:
    git: []
    postgresql93-devel: []
    ImageMagick: []
    ImageMagick-devel: []

container_commands:
  01_reload_nginx:
    command: "service nginx reload"
